version: '3.9'
services:
  web:
    build: .
    command: ./docker-entrypoint.sh
    ports:
      - 8000:8000
    # depends_on:
    #   - redis
    restart: on-failure
    volumes:
      - .:/app
  # redis:
  #   image: redis:6.2-alpine
  #   ports:
  #     - 6379:6379
  #   restart: always
  #   volumes:
  #     - redisdata:/data
# volumes:
#   redisdata:    
